var items = [  'Sugar refined',
  'Beans, dry',
  'Bread',
  'Cake, soybeans',
  'Crude materials',
  'Groundnuts, shelled',
  'Lemons and limes',
  'Maize',
  'Nuts, prepared (exc. groundnuts)',
  'Offals, edible, cattle',
  'Oil, sunflower',
  'Pastry',
  'Plums dried (prunes)',
  'Sugar confectionery',
  'Fat, nes, prepared',
  'Juice, fruit nes',
  'Margarine, short',
  'Chickens',
  'Almonds shelled',
  'Anise, badian, fennel, coriander',
  'Beer of barley',
  'Beverages, non alcoholic',
  'Butter, cow milk',
  'Buttermilk, curdled, acidified milk',
  'Cereals, breakfast',
  'Cheese, processed',
  'Chocolate products nes',
  'Coffee, extracts',
  'Coffee, roasted',
  'Feed and meal, gluten',
  'Flour, mustard',
  'Flour, potatoes',
  'Food prep nes',
  'Food wastes',
  'Fruit, dried nes',
  'Fruit, prepared nes',
  'Glucose and dextrose',
  'Honey, natural',
  'Hops',
  'Infant food',
  'Juice, citrus, concentrated',
  'Juice, grapefruit',
  'Juice, orange, single strength',
  'Juice, pineapple',
  'Macaroni',
  'Malt',
  'Meat, chicken',
  'Meat, chicken, canned',
  'Meat, pig sausages',
  'Meat, pig, preparations',
  'Mushrooms, canned',
  'Oil, olive, virgin',
  'Oil, palm',
  'Oilseeds nes',
  'Onions, dry',
  'Pepper (piper spp.)',
  'Pet food',
  'Potatoes',
  'Spices, nes',
  'Sugar, nes',
  'Sunflower seed',
  'Tea',
  'Tea, mate extracts',
  'Vegetables in vinegar',
  'Vegetables, dehydrated',
  'Vegetables, homogenized preparations',
  'Vegetables, preserved nes',
  'Vegetables, preserved, frozen',
  'Wafers',
  'Waters,ice etc',
  'Wine',
  'Beehives',
  'Beverages, distilled alcoholic',
  'Cider etc',
  'Cocoa, butter',
  'Fatty acids',
  'Food preparations, flour, malt extract',
  'Grease incl. lanolin wool',
  'Ice cream and edible ice',
  'Lactose',
  'Meat, beef, preparations',
  'Meat, pig',
  'Milk, products of natural constituents nes',
  'Milk, skimmed dried',
  'Milk, whole dried',
  'Milk, whole fresh cow',
  'Mixes and doughs',
  'Oil, linseed',
  'Potatoes, frozen',
  'Rice – total  (Rice milled equivalent)',
  'Skins, sheep, with wool',
  'Tobacco products nes',
  'Vegetables, frozen',
  'Whey, dry',
  'Bacon and ham',
  'Cheese, whole cow milk',
  'Cream fresh',
  'Fruit, cooked, homogenized preparations',
  'Milk, skimmed cow',
  'Wheat',
  'Yoghurt, concentrated or not',
  'Coffee, green',
  'Flour, wheat',
  'Mangoes, mangosteens, guavas',
  'Meat, cattle',
  'Meat, cattle, boneless (beef & veal)',
  'Meat, pork',
  'Melons, other (inc.cantaloupes)',
  'Molasses',
  'Offals, pigs, edible',
  'Papayas',
  'Cattle',
  'Buckwheat',
  'Cake, sunflower',
  'Cereal preparations, nes',
  'Cigarettes',
  'Cinnamon (canella)',
  'Cocoa, powder & cake',
  'Lentils',
  'Oats',
  'Oats rolled',
  'Oil, olive residues',
  'Poppy seed',
  'Raisins',
  'Rye',
  'Sesame seed',
  'Tomatoes, peeled',
  'Walnuts, shelled',
  'Walnuts, with shell',
  'Cashew nuts, shelled',
  'Avocados',
  'Oranges',
  'Grapes',
  'Kiwi fruit',
  'Meat, sheep',
  'Pears',
  'Plums and sloes',
  'Bananas',
  'Pineapples',
  'Pigs',
  'Eggplants (aubergines)',
  'Fructose and syrup, other',
  'Pineapples canned',
  'Sweet corn frozen',
  'Cigars, cheroots',
  'Soya sauce',
  'Sweet corn prep or preserved',
  'Plantains',
  'Beet pulp',
  'Cloves',
  'Dates',
  'Hides, cattle, wet salted',
  'Goats',
  'Turkeys',
  'Eggs, hen, in shell',
  'Juice, grapefruit, concentrated',
  'Juice, orange, concentrated',
  'Juice, pineapple, concentrated',
  'Meat, duck',
  'Oil, essential nes',
  'Oil, rapeseed',
  'Oil, vegetable origin nes',
  'Olives preserved',
  'Soybeans',
  'Mules',
  'Bran, wheat',
  'Chillies and peppers, dry',
  'Chillies and peppers, green',
  'Copra',
  'Flour, cereals',
  'Germ, maize',
  'Juice, citrus, single strength',
  'Jute',
  'Linseed',
  'Maté',
  'Milk, whole condensed',
  'Milk, whole evaporated',
  'Oil, boiled etc',
  'Oil, coconut (copra)',
  'Oil, cottonseed',
  'Sugar Raw Centrifugal',
  'Vanilla',
  'Vegetables, fresh or dried products nes',
  'Vermouths & similar',
  'Ducks',
  'Sheep',
  'Rabbits and hares',
  'Apples',
  'Apricots',
  'Apricots, dry',
  'Beans, green',
  'Beeswax',
  'Bran, maize',
  'Broad beans, horse beans, dry',
  'Cabbages and other brassicas',
  'Cake, cottonseed',
  'Carrots and turnips',
  'Cauliflowers and broccoli',
  'Cherries',
  'Cherries, sour',
  'Chestnut',
  'Chick peas',
  'Coconuts',
  'Coconuts, desiccated',
  'Cotton lint',
  'Cotton waste',
  'Cotton, carded, combed',
  'Cottonseed',
  'Cranberries',
  'Cucumbers and gherkins',
  'Eggs, dried',
  'Eggs, liquid',
  'Fat, pigs',
  'Feed, vegetable products nes',
  'Figs dried',
  'Flax tow waste',
  'Flour, maize',
  'Fruit, fresh nes',
  'Garlic',
  'Grapefruit (inc. pomelos)',
  'Hazelnuts, shelled',
  'Juice, grape',
  'Juice, tomato',
  'Lettuce and chicory',
  'Maple sugar and syrups',
  'Meal, meat',
  'Mushrooms and truffles',
  'Nuts, nes',
  'Oil, groundnut',
  'Oil, maize',
  'Oil, sesame',
  'Oil, soybean',
  'Oils, fats of animal nes',
  'Olives',
  'Peaches and nectarines',
  'Persimmons',
  'Pistachios',
  'Pumpkins, squash and gourds',
  'Quinces',
  'Roots and tubers, nes',
  'Rubber natural dry',
  'Spinach',
  'Straw husks',
  'Strawberries',
  'Tangerines, mandarins, clementines, satsumas',
  'Tomatoes',
  'Tomatoes, paste',
  'Vegetables, fresh nes',
  'Vegetables, temporarily preserved',
  'Watermelons',
  'Nutmeg, mace and cardamoms',
  'Canary seed',
  'Millet',
  'Rapeseed',
  'Cake, copra',
  'Horses',
  'Artichokes',
  'Asparagus',
  'Barley',
  'Coffee, substitutes containing coffee',
  'Cotton linter',
  'Eggs, other bird, in shell',
  'Fat, cattle',
  'Fatty substance residues',
  'Flax fibre and tow',
  'Lard',
  'Leeks, other alliaceous vegetables',
  'Meat, game',
  'Meat, goose and guinea fowl',
  'Meat, horse',
  'Meat, nes',
  'Meat, turkey',
  'Offals, liver geese',
  'Oil, castor beans',
  'Peas, dry',
  'Peas, green',
  'Tallow',
  'Oil, palm kernel',
  'Offals, liver duck',
  'Waxes vegetable',
  'Ginger',
  'Brazil nuts, shelled',
  'Sorghum',
  'Tobacco, unmanufactured',
  'Coffee, husks and skins',
  'Fruit, tropical fresh nes',
  'Cocoa, beans',
  'Mustard seed',
  'Buffaloes',
  'Cocoa, paste',
  'Forage products',
  'Onions, shallots, green',
  'Rubber, natural',
  'Triticale',
  'Animals live nes',
  'Offals, sheep,edible',
  'Flour, pulses',
  'Alfalfa meal and pellets',
  'Figs',
  'Dregs from brewing, distillation',
  'Feed supplements',
  'Juice, lemon, concentrated',
  'Meat, dried nes',
  'Sweet potatoes',
  'Wool, greasy',
  'Hair, fine',
  'Wool, degreased',
  'Starch, cassava',
  'Hides, nes',
  'Silk raw',
  'Oil, safflower',
  'Blueberries',
  'Offals, liver chicken',
  'Peanut butter',
  'Currants',
  'Maize, green',
  'Feed, compound, nes',
  'Meat, goat',
  'Cassava dried',
  'Flour, roots and tubers nes',
  'Cake, palm kernel',
  'Sugar beet',
  'Cocoons, unreelable & waste',
  'Hay (unspecified)',
  'Fat, liver prepared (foie gras)',
  'Meat, rabbit',
  'Cake, rapeseed',
  'Feed, pulp of fruit',
  'Whey, condensed',
  'Kola nuts',
  'Bambara beans',
  'Barley, pearled',
  'Cake, groundnuts',
  'Cake, linseed',
  'Cashew nuts, with shell',
  'Flax fibre raw',
  'Fonio',
  'Silk-worm cocoons, reelable',
  'Wool, hair waste',
  'Camels',
  'Skins, calve, wet salted',
  'Flour, mixed grain',
  'Skins, sheep, dry salted',
  'Asses',
  'Meat, beef and veal sausages',
  'Offals, edible, goats',
  'Offals, other camelids',
  'Skins, sheep, wet salted',
  'Beverages, fermented rice',
  'Camelids, other',
  'Sugar crops, nes',
  'Margarine, liquid',
  'Sugar non-centrifugal',
  'Gooseberries',
  'Oil, rice bran',
  'Grain, mixed',
  'Pyrethrum, dried',
  'Cake, mustard',
  'Cake, maize',
  'Bulgur',
  'Manila fibre (abaca)',
  'Cake, rice bran',
  'Rodents, other',
  'Oil, citronella' ]

  items.sort();

